# .github/workflows/deploy-lemobici-api.yml
name: Deploy Lemobici API

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Transfer to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "."
          target: "/opt/lemobici/lemobici-api-temp"
          overwrite: true
          tar_args: "--exclude='.git*'"

      - name: Deploy with zero downtime
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /opt/lemobici

            docker compose up --build api 

            echo "Deployment API finished ---1⚔️---"
